# Hubbamax theme
set-option -g status-style "bg=#1c1c1c,fg=#bcbcbc"
set -g status-right '%H:%M %Y-%b-%d'
set-option -g status-left "#[bg=#87afaf,fg=#1c1c1c,bold] #S #[default] "
set -g window-status-format "#[fg=#9e9e9e,bg=#1c1c1c] #I:#W "
set -g window-status-current-format "#[fg=#1c1c1c,bg=#87afaf,bold] #I:#W "
set -g pane-border-style "fg=#303030"
set -g pane-active-border-style "fg=#87afaf"
