# Rose Pine theme from https://github.com/rose-pine/tmux
set -g @rose_pine_variant 'main'
set -g @rose_pine_date_time '%H:%M %Y-%b-%d'
set -g @rose_pine_disable_active_window_menu 'on'
run-shell ~/.config/tmux/themes/rose-pine.tmux
