set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'


set-option -sa terminal-overrides ",xterm*:Tc"
set -sg escape-time 0
set -g history-limit 200000
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# :theme
# set -g @rose_pine_variant 'main' # Options are 'main', 'moon' or 'dawn'
# set -g @tmux-gruvbox 'dark' # or 'dark256', 'light', 'light256'
# set -g @rose_pine_disable_active_window_menu 'on' # Disables the menu that shows the active window on the left

# :status-style
set-option -g status-style "bg=#1c1c1c,fg=#bcbcbc"
set -g status-right '%H:%M %Y-%b-%d'
set-option -g status-left "#[bg=#87afaf,fg=#1c1c1c,bold] #S #[default] "
set -g window-status-format "#[fg=#9e9e9e,bg=#1c1c1c] #I:#W "
set -g window-status-current-format "#[fg=#1c1c1c,bg=#87afaf,bold] #I:#W "
set -g pane-border-style "fg=#303030"
set -g pane-active-border-style "fg=#87afaf"

set -g mouse on

unbind p
bind -n C-h previous-window

unbind n
bind -n C-l next-window

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"


# Enable Vim key bindings in copy mode
set -g mode-keys vi

# Set copy mode key binding (Ctrl+b [ to enter copy mode)
bind-key -T copy-mode-vi v send -X begin-selection # Start selection with 'v'
bind-key -T copy-mode-vi y send -X copy-selection  # Yank/copy with 'y'

bind-key -n C-S-o display-popup -E "~/.config/tmux/plugins/tmux-session/tmux-fzf.sh"

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm' 
